# Generated by Django 2.1.1 on 2018-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_post_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='image',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
