# Generated by Django 2.1.1 on 2018-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_perso_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='desc',
        ),
        migrations.AddField(
            model_name='maison',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='maison',
            name='influence',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='maison',
            name='prestige',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nom',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
