# Generated by Django 2.1.1 on 2018-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180919_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(default='')),
                ('one_use', models.BooleanField(default=False)),
                ('arme_OK', models.BooleanField(default=False)),
                ('armure_OK', models.BooleanField(default=False)),
                ('en_main_OK', models.BooleanField(default=False)),
                ('bonus_attaque_duel', models.SmallIntegerField(default=0)),
                ('bonus_defense_duel', models.SmallIntegerField(default=0)),
                ('bonus_defense_melee', models.SmallIntegerField(default=0)),
                ('bonus_attaque_melee', models.SmallIntegerField(default=0)),
                ('bonus_initiative', models.SmallIntegerField(default=0)),
                ('bonus_PA', models.SmallIntegerField(default=0)),
                ('niveau_armurerie', models.SmallIntegerField(default=0)),
                ('solidite', models.SmallIntegerField(default=1)),
                ('niveau_sorcellerie', models.SmallIntegerField(default=0)),
                ('niveau_alchimie', models.SmallIntegerField(default=0)),
                ('pouvoir', models.CharField(max_length=30)),
                ('puissance', models.SmallIntegerField(default=1)),
                ('volume', models.SmallIntegerField(default=1)),
                ('bonus_officier', models.SmallIntegerField(default=0)),
                ('bonus_soins', models.SmallIntegerField(default=0)),
                ('bonus_regeneration', models.SmallIntegerField(default=0)),
                ('bonus_concentration', models.SmallIntegerField(default=0)),
                ('bonus_aura', models.SmallIntegerField(default=0)),
                ('bonus_savoir', models.SmallIntegerField(default=0)),
                ('bonus_fouille', models.SmallIntegerField(default=0)),
                ('bonus_enquete', models.SmallIntegerField(default=0)),
                ('bonus_intrusion', models.SmallIntegerField(default=0)),
                ('bonus_dissimulation', models.SmallIntegerField(default=0)),
                ('bonus_fuite', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
