# Generated by Django 2.1.1 on 2018-09-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180922_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='Suzerain',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='maison',
            name='deesse',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='maison',
            name='embleme',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='maison',
            name='image_embleme',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='maison',
            name='image_illu',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='maison',
            name='institutions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
