# Generated by Django 2.1.1 on 2018-09-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20180922_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='deesse',
            new_name='dieu',
        ),
    ]
