# Generated by Django 2.1.1 on 2018-09-29 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0011_auto_20180926_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('MJ', 'MJ'), ('PNJ', 'PNJ'), ('PJ', 'PJ')], default='PJ', max_length=30)),
                ('allie', models.ManyToManyField(blank=True, related_name='_joueur_allie_+', to='forum.Joueur')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
