# Generated by Django 2.1.1 on 2018-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20180929_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='users_connaissants',
            field=models.ManyToManyField(blank=True, related_name='users_connaissants', to='forum.Joueur'),
        ),
    ]
