# Generated by Django 2.1.1 on 2018-09-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20180929_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='user',
        ),
        migrations.AddField(
            model_name='perso',
            name='joueur',
            field=models.ManyToManyField(blank=True, to='forum.Joueur'),
        ),
    ]
