# Generated by Django 2.1.1 on 2018-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20180929_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='background',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='background',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='perso',
            name='background',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='persos_cible',
            field=models.ManyToManyField(blank=True, related_name='users_cible', to='forum.Joueur'),
        ),
    ]
