# Generated by Django 2.1.1 on 2018-09-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20180930_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='etat_sante',
            field=models.CharField(choices=[('Mort', 'Mort'), ('Inconscient', 'Inconscient'), ('Gravement Blesse', 'Gravement Blesse'), ('Blesse', 'Blesse'), ('En bonne sante', 'En bonne sante')], default='En bonne sante', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='perso',
            name='situation',
            field=models.CharField(choices=[('', 'RAS'), ('Accompagnant', 'Accompagnant'), ('Prisonnier(e)', 'Prisonnier(e)'), ('En situation de combat', 'En situation de combat')], default='', max_length=30),
        ),
    ]
