# Generated by Django 2.1.1 on 2018-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_categorie_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sante',
            name='PV',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
    ]
