# Generated by Django 2.1.1 on 2018-10-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20181003_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='maison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Maison'),
        ),
    ]
