# Generated by Django 2.1.1 on 2018-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20181003_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='priorite',
            field=models.SmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='priorite_temp',
            field=models.PositiveIntegerField(default=9, editable=False),
        ),
    ]
