# Generated by Django 2.1.1 on 2018-10-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20181006_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_perso',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Perso'),
        ),
        migrations.AlterField(
            model_name='post',
            name='texte',
            field=models.TextField(verbose_name=''),
        ),
    ]
