# Generated by Django 2.1.1 on 2018-10-19 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_auto_20181015_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=30)),
                ('dissimulation', models.SmallIntegerField(default=0)),
                ('en_attente', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='persos_cible',
            new_name='joueur_connaissant',
        ),
        migrations.RemoveField(
            model_name='action',
            name='competences_utiles',
        ),
        migrations.RemoveField(
            model_name='action',
            name='is_lieu',
        ),
        migrations.RemoveField(
            model_name='action',
            name='is_objet',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='accompagnants',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_perso',
        ),
        migrations.RemoveField(
            model_name='post',
            name='valide',
        ),
        migrations.AddField(
            model_name='action',
            name='condition_competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Competence'),
        ),
        migrations.AddField(
            model_name='perso',
            name='actions_possibles',
            field=models.ManyToManyField(blank=True, related_name='actions_possibles', to='forum.Action'),
        ),
        migrations.AddField(
            model_name='perso',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perso',
            name='en_combat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perso',
            name='nbGardes_MAX',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perso',
            name='nbTroupes_MAX',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perso',
            name='occupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perso',
            name='perso_accompagnants',
            field=models.ManyToManyField(blank=True, related_name='_perso_perso_accompagnants_+', to='forum.Perso'),
        ),
        migrations.AddField(
            model_name='perso',
            name='perso_prisonnier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Perso'),
        ),
        migrations.AddField(
            model_name='perso',
            name='vivant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='css',
            field=models.CharField(default='PostNormal', max_length=30),
        ),
        migrations.RemoveField(
            model_name='action',
            name='condition_lieu',
        ),
        migrations.AddField(
            model_name='action',
            name='condition_lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Lieu'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='prisonnier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Action'),
        ),
        migrations.AddField(
            model_name='commande',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='lieu_post', to='forum.Lieu'),
        ),
        migrations.AddField(
            model_name='commande',
            name='lieu_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lieu_cible', to='forum.Lieu'),
        ),
        migrations.AddField(
            model_name='commande',
            name='perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Perso'),
        ),
        migrations.AddField(
            model_name='commande',
            name='persos_cible',
            field=models.ManyToManyField(blank=True, related_name='persos_cible', to='forum.Joueur'),
        ),
    ]
