# Generated by Django 2.1.1 on 2018-11-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_auto_20181019_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='PA',
        ),
        migrations.RemoveField(
            model_name='action',
            name='cible_action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='condition_lieu',
        ),
        migrations.AddField(
            model_name='action',
            name='PV_max',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='action',
            name='PV_min',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_atelier_ET_competence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_en_combat',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est en combat ou non'), (1, "Ne peut etre fait que si le perso n'est pas en combat"), (2, 'Ne peut être fait que si le perso est en combat')], default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_en_soin',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est en soin ou non'), (1, "Ne peut etre fait que si le perso n'est pas en soin"), (2, 'Ne peut être fait que si le perso est en soin')], default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_occupe',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est occupe ou non'), (1, "Ne peut etre fait que si le perso n'est pas occupe"), (2, 'Ne peut être fait que si le perso est occupe')], default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_prisonnier',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est prisonnier ou non'), (1, "Ne peut etre fait que si le perso n'est pas prisonnier"), (2, 'Ne peut être fait que si le perso est prisonnier')], default=1),
        ),
        migrations.AddField(
            model_name='commande',
            name='joueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Joueur'),
        ),
        migrations.AddField(
            model_name='perso',
            name='en_soin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Atelier'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Atelier'),
        ),
    ]
