# Generated by Django 2.1.1 on 2018-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_auto_20181101_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='espece',
        ),
    ]
