# Generated by Django 2.1.1 on 2018-11-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_remove_perso_espece'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='espece',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espece', to='forum.Espece'),
        ),
    ]
