# Generated by Django 2.1.1 on 2018-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_auto_20181103_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='ciblelieu_acote',
            new_name='ciblelieu_eloigne',
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_QG',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être un QG ou non'), (1, 'Le lieu cible ne doit pas être un QG'), (2, 'Le lieu cible doit être un QG')], default=0, verbose_name="Cible Lieu : est le QG d'une maison ?"),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_a_garde',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut avoir des gardes ou non'), (1, 'Le lieu cible ne doit pas avoir de gardes'), (2, 'Le lieu cible doit avoir des gardes')], default=0, verbose_name='Cible Lieu : a des gardes ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_a_troupe',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut avoir des troupes ou non'), (1, 'Le lieu cible ne doit pas avoir de troupes'), (2, 'Le lieu cible doit avoir des troupes')], default=0, verbose_name='Cible Lieu : a des troupes ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_espace',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être un espace ouvert ou non'), (1, 'Le lieu cible ne doit pas être un espace ouvert'), (2, 'Le lieu cible doit être un espace ouvert')], default=1, verbose_name='Cible Lieu : est un espace ouvert ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_ferme',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être fermé ou non'), (1, 'Le lieu cible ne doit pas être fermé'), (2, 'Le lieu cible doit être fermé')], default=1, verbose_name='Cible Lieu : est fermé ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_inconnu',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être un lieu inconnu ou non'), (1, 'Le lieu cible ne doit pas être un lieu inconnu'), (2, 'Le lieu cible doit être un lieu inconnu')], default=1, verbose_name='Cible Lieu : est inconnu ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_invite',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être fermé au perso ou non'), (1, 'Le lieu cible ne doit pas être fermé au perso'), (2, 'Le lieu cible doit être fermé au perso')], default=1, verbose_name="Cible Lieu : le perso a le droit d'entrer ?"),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_proprietaire',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être la poprieté du perso ou non'), (1, 'Le lieu cible ne doit pas être la poprieté du perso'), (2, 'Le lieu cible doit être la poprieté du perso')], default=0, verbose_name='Cible Lieu : la maison du perso en est proprietaire ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='ciblelieu_secret',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être un lieu secret ou non'), (1, 'Le lieu cible ne doit pas être un lieu secret'), (2, 'Le lieu cible doit être un lieu secret')], default=0, verbose_name='Cible Lieu : est secret ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='cibleperso_a_gardes',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut avoir des gardes ou non'), (1, 'La cible ne doit pas avoir de gardes'), (2, 'La cible doit avoir des gardes')], default=0, verbose_name='Cible Perso : a des gardes ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='cibleperso_a_troupes',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut avoir des troupes ou non'), (1, 'La cible ne doit pas avoir de troupes'), (2, 'La cible doit avoir des troupes')], default=0, verbose_name='Cible Perso : a des troupes ?'),
        ),
        migrations.AddField(
            model_name='action',
            name='cibleperso_cache',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut être caché ou non'), (1, 'La cible ne doit pas être cachée aux yeux du perso acteur'), (2, 'La cible doit être cachées aux yeux du perso acteur')], default=0, verbose_name='Cible Perso : est caché ?'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='QG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieu',
            name='espace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perso',
            name='joueur_repere',
            field=models.ManyToManyField(blank=True, related_name='joueur_repere', to='forum.Joueur'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cibleperso_prisonnier',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut être prisonnier ou non'), (1, 'La cible ne doit pas être prisonnier par un tiers'), (2, 'La cible doit être prisonnier par le perso acteur')], default=1, verbose_name='Cible Perso : prisonnier ?'),
        ),
    ]
