# Generated by Django 2.1.1 on 2018-11-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_auto_20181103_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='persos_cible',
            field=models.ManyToManyField(blank=True, related_name='persos_cible', to='forum.Perso'),
        ),
    ]
