# Generated by Django 2.1.1 on 2018-11-03 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_auto_20181103_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(default=datetime.timedelta(0, 3600)),
        ),
    ]
