# Generated by Django 2.1.1 on 2018-11-03 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_auto_20181103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
