# Generated by Django 2.1.1 on 2018-11-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_auto_20181103_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True, verbose_name='Nom de la partie')),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_info', models.CharField(max_length=30, unique=True, verbose_name='Nom informatique - lien vers static')),
                ('base_delay', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Délai pour une action courante, en heure')),
            ],
        ),
    ]
