# Generated by Django 2.1.1 on 2018-11-09 20:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0041_auto_20181107_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phrase de description lors de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='jeu',
            name='format_date',
            field=models.CharField(default='<heure>h<minute>, <jour> jour <mois>', max_length=40, verbose_name='Phrase de description de la date'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='nb_heure_jour',
            field=models.SmallIntegerField(default=10, verbose_name="Nombre d'heures de jour"),
        ),
        migrations.AddField(
            model_name='jeu',
            name='nb_heure_nuit',
            field=models.SmallIntegerField(default=10, verbose_name="Nombre d'heures de nuit"),
        ),
        migrations.AddField(
            model_name='post',
            name='date_jeu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='chance_reussite',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='annee_jeu_init',
            field=models.SmallIntegerField(default=99, verbose_name='Date jeu initiale : année'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='date_initiale',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date réelle initiale'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='heure_jeu_init',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Date jeu initiale : heure'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='jour_jeu_init',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Date jeu initiale : jour'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='jour_par_mois',
            field=models.SmallIntegerField(default=31, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de jour par mois'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='mois_jeu_init',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Mois', verbose_name='Date jeu initiale : mois'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='mois_par_an',
            field=models.SmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de mois par an'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='occupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_perso', to='forum.Commande'),
        ),
    ]
