# Generated by Django 2.1.1 on 2018-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_auto_20181109_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_validation',
        ),
        migrations.AddField(
            model_name='action',
            name='msg_fin',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phrase de description lors de la fin de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AddField(
            model_name='action',
            name='msg_init',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phrase de description lors du début de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phrase de description sur la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='format_date',
            field=models.CharField(default='<heure>h<minute>, <jour> jour <mois>', max_length=40, verbose_name='Phrase de description de la date <minute><heure><jour><mois><annee>'),
        ),
    ]
