# Generated by Django 2.1.1 on 2018-11-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0044_commande_date_jeu_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='lieu',
        ),
    ]
