# Generated by Django 2.1.1 on 2018-11-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0046_auto_20181112_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perso',
            old_name='PVA',
            new_name='PC',
        ),
        migrations.RemoveField(
            model_name='action',
            name='msg_MJ',
        ),
        migrations.RemoveField(
            model_name='action',
            name='msg_resume',
        ),
        migrations.RemoveField(
            model_name='action',
            name='signal_MJ',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='PVA_MAX',
        ),
        migrations.RemoveField(
            model_name='post',
            name='css',
        ),
        migrations.AddField(
            model_name='action',
            name='annulable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='chance_reussite',
            field=models.SmallIntegerField(default=100, verbose_name="chance de réussite sur l'action, en %"),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_geolier',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso a un prisonnier ou non'), (1, "Ne peut etre fait que si le perso n'a pas de prisonnier"), (2, 'Ne peut être fait que si le perso a un prisonnier')], default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_hote',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est un hote de lieu ou non'), (1, "Ne peut etre fait que si le perso n'est pas un hote de lieu"), (2, 'Ne peut être fait que si le perso est un hote de lieu')], default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='est_combat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='importance',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='msg_encours',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Phrase de description lors du début de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='joueur_connaissant',
            field=models.ManyToManyField(blank=True, related_name='joueur_know_commande', to='forum.Joueur'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='defense_assault_max',
            field=models.SmallIntegerField(default=5, verbose_name="Valeur maximale de la defense d'un lieu standard"),
        ),
        migrations.AddField(
            model_name='lieu',
            name='defense_assault_bonusmax',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lieu',
            name='users_connaissants_place',
            field=models.ManyToManyField(blank=True, related_name='users_connaissants_place', to='forum.Joueur'),
        ),
        migrations.AddField(
            model_name='perso',
            name='hote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hote', to='forum.Lieu'),
        ),
        migrations.AddField(
            model_name='perso',
            name='info_signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='action',
            name='delay',
            field=models.SmallIntegerField(default=100, verbose_name="temps pour réaliser l'action, en %"),
        ),
        migrations.AlterField(
            model_name='action',
            name='msg_fin',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Phrase de description lors de la fin de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AlterField(
            model_name='action',
            name='msg_init',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Phrase de description lors du début de la commande (#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='chance_reussite',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='inconnu',
            field=models.BooleanField(default=True, verbose_name="INCONNU : a besoin d'être visité pour être dans la carte ?"),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='SECRET : le passage pour y accéder est secret ?'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='PA_MAX',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='joueur_connaissant',
            field=models.ManyToManyField(blank=True, related_name='joueur_know_post', to='forum.Joueur'),
        ),
    ]
