# Generated by Django 2.1.1 on 2018-11-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_auto_20181114_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='cible_heure',
            new_name='cible_instant',
        ),
        migrations.AddField(
            model_name='action',
            name='champ_recherche1_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='champ_recherche2_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='champ_texte_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='cible_instant_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='cible_lieu_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='cible_perso_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='texte_explicatif_choix',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Phrase qui va expliquer le choix'),
        ),
        migrations.AddField(
            model_name='commande',
            name='bonus_reussite',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='champ_recherche1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='champ_recherche2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='champ_texte',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='instant_heure',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='instant_jour',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='instant_mois',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Mois'),
        ),
    ]
