# Generated by Django 2.1.3 on 2018-11-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0050_auto_20181121_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='commande',
            name='jet',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='jet_opposition',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
