# Generated by Django 2.1.3 on 2018-11-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0051_auto_20181122_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='txt_joueurs_connaissant',
            field=models.TextField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='instant_mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Mois'),
        ),
    ]
