# Generated by Django 2.1.3 on 2018-11-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0052_auto_20181126_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='txt_joueurs_connaissant',
        ),
        migrations.AddField(
            model_name='commande',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='commande_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Commande'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
