# Generated by Django 2.1.3 on 2018-11-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0054_auto_20181128_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='commande_precede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_enclenche', to='forum.Commande', verbose_name='Commande précédent le lancement'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='commande_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associe', to='forum.Commande'),
        ),
    ]
