# Generated by Django 2.1.3 on 2018-12-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0056_categorie_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_parent',
        ),
        migrations.AddField(
            model_name='action',
            name='categorie',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Categorie_action'),
        ),
    ]
