# Generated by Django 2.1.3 on 2018-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0057_auto_20181204_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
