# Generated by Django 2.1.3 on 2018-12-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0058_lieu_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='acion_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Action'),
        ),
    ]
