# Generated by Django 2.1.3 on 2018-12-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0059_action_acion_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='acion_parent',
            new_name='action_parent',
        ),
    ]
