# Generated by Django 2.1.3 on 2018-12-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0060_auto_20181204_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='options',
            field=models.BooleanField(default=False, verbose_name='a des options'),
        ),
    ]
