# Generated by Django 2.1.3 on 2018-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0065_perso_persos_deja_provoques'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition_en_fuite',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est en fuite ou non'), (1, "Ne peut etre fait que si le perso n'est pas en fuite"), (2, 'Ne peut être fait que si le perso est en fuite')], default=1),
        ),
        migrations.AddField(
            model_name='perso',
            name='en_fuite',
            field=models.BooleanField(default=False),
        ),
    ]
