# Generated by Django 2.1.3 on 2018-12-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0066_auto_20181214_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='fuite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieu_fuite', to='forum.Lieu', verbose_name='Lieu de fuite'),
        ),
    ]
