# Generated by Django 2.1.3 on 2018-12-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0067_lieu_fuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition_en_duel',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est en duel ou non'), (1, "Ne peut etre fait que si le perso n'est pas en duel"), (2, 'Ne peut être fait que si le perso est en duel')], default=1),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Action', verbose_name="Action parent : cette action se rattache en tant qu'option à une autre action"),
        ),
    ]
