# Generated by Django 2.1.3 on 2018-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0068_auto_20181218_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='instant_heure',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='instant_jour',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
