# Generated by Django 2.1.3 on 2018-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0069_auto_20181218_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='desc2',
            field=models.TextField(blank=True, default='', verbose_name='Phrase de description sur la commande vue par le perso cible(#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
        migrations.AddField(
            model_name='perso',
            name='desc_occupe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phrase de description sur la commande vue par le perso acteur(#perso# , #lieu# , #persos_cible# , #lieux_cible#)'),
        ),
    ]
