# Generated by Django 2.1.3 on 2018-12-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0070_auto_20181219_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='prestige',
            new_name='influence_senat',
        ),
    ]
