# Generated by Django 2.1.1 on 2018-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0073_auto_20181220_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='dissimulable',
        ),
        migrations.AddField(
            model_name='action',
            name='condition_cache',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso est caché ou non'), (1, "Ne peut etre fait que si le perso n'est pas caché"), (2, 'Ne peut être fait que si le perso est caché')], default=0),
        ),
    ]
