# Generated by Django 2.1.3 on 2019-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0074_auto_20181225_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
