# Generated by Django 2.1.3 on 2019-01-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0075_joueur_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='persos_cible',
            field=models.ManyToManyField(blank=True, related_name='perso_cible_post', to='forum.Perso'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='lieu_post', to='forum.Lieu'),
        ),
    ]
