# Generated by Django 2.1.3 on 2019-01-18 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0076_auto_20190114_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=200)),
                ('texte', models.TextField(verbose_name='')),
                ('date_jeu', models.CharField(blank=True, default='', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Joueur')),
                ('joueurs_affiche', models.ManyToManyField(blank=True, related_name='joueur_affiche_message', to='forum.Joueur')),
                ('joueurs_cible', models.ManyToManyField(related_name='joueur_cible_message', to='forum.Joueur')),
            ],
        ),
    ]
