# Generated by Django 2.1.1 on 2019-01-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0077_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='joueurs_nonlu',
            field=models.ManyToManyField(blank=True, related_name='joueur_non_lu', to='forum.Joueur'),
        ),
    ]
