# Generated by Django 2.1.3 on 2019-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0078_message_joueurs_nonlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='priorite',
            field=models.SmallIntegerField(default=9),
        ),
    ]
