# Generated by Django 2.1.3 on 2019-01-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0079_maison_priorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='senateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senateur', to='forum.Perso'),
        ),
    ]
