# Generated by Django 2.1.3 on 2019-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0080_auto_20190121_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
