# Generated by Django 2.1.3 on 2019-01-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0081_maison_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='image_embleme',
        ),
        migrations.AlterField(
            model_name='perso',
            name='etat_sante',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Sante'),
        ),
    ]
