# Generated by Django 2.1.3 on 2019-01-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0082_auto_20190124_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='image_illu',
            new_name='nom_info',
        ),
        migrations.AddField(
            model_name='competence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Categorie_competence'),
        ),
    ]
