# Generated by Django 2.1.3 on 2019-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0083_auto_20190124_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='categorie',
        ),
        migrations.AddField(
            model_name='competence',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='forum.Categorie_competence'),
        ),
    ]
