# Generated by Django 2.1.3 on 2019-01-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0084_auto_20190124_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='bonus_competence1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_competence1', to='forum.Competence'),
        ),
        migrations.AddField(
            model_name='maison',
            name='bonus_competence2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_competence2', to='forum.Competence'),
        ),
        migrations.AddField(
            model_name='maison',
            name='bonus_competence_categorie1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_competence_categorie1', to='forum.Categorie_competence'),
        ),
        migrations.AddField(
            model_name='maison',
            name='bonus_competence_categorie2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_competence_categorie2', to='forum.Categorie_competence'),
        ),
    ]
