# Generated by Django 2.1.3 on 2019-01-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0088_joueur_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Lieu'),
        ),
    ]
