# Generated by Django 2.1.3 on 2019-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0089_commande_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='nb_posts_par_page',
            field=models.SmallIntegerField(default=30),
        ),
    ]
