# Generated by Django 2.1.3 on 2019-02-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0090_joueur_nb_posts_par_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nom_info',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name="Nom informatique (image) - si =='' : rien n'est associé "),
        ),
    ]
