# Generated by Django 2.1.3 on 2019-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0092_resultat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='post',
        ),
        migrations.AddField(
            model_name='resultat',
            name='texte',
            field=models.TextField(default='', null=True, verbose_name='Description MJ'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='cle1',
            field=models.CharField(blank=True, max_length=300, verbose_name="Clé 1 - ';' sépare les entités "),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='cle2',
            field=models.CharField(blank=True, max_length=300, verbose_name="Clé 2 - ';' sépare les entités "),
        ),
    ]
