# Generated by Django 2.1.3 on 2019-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0093_auto_20190206_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='cle_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Clé Date'),
        ),
    ]
