# Generated by Django 2.1.3 on 2019-02-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0094_auto_20190206_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='dommage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Autre'), (1, 'Fouille'), (2, 'Bibliotheque'), (3, 'Enquete'), (3, 'Exploration')], default=1),
        ),
    ]
