# Generated by Django 2.1.3 on 2019-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0096_auto_20190208_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='atelier',
            field=models.ManyToManyField(blank=True, related_name='atelier_lieu', to='forum.Atelier'),
        ),
        migrations.AlterField(
            model_name='loi',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
