# Generated by Django 2.1.3 on 2019-02-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0097_auto_20190208_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='loi',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Lieu'),
        ),
    ]
