# Generated by Django 2.1.3 on 2019-02-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0098_loi_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='Objets',
        ),
        migrations.AddField(
            model_name='commande',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultat', to='forum.Resultat'),
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='objet_trouve',
        ),
        migrations.AddField(
            model_name='resultat',
            name='objet_trouve',
            field=models.ManyToManyField(blank=True, related_name='objet_trouve', to='forum.Objet'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='texte',
            field=models.TextField(default='', null=True, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Autre'), (1, 'Fouille'), (2, 'Bibliotheque'), (3, 'Enquete'), (1, 'Etude'), (3, 'Exploration')], default=1),
        ),
    ]
