# Generated by Django 2.1.3 on 2019-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0099_auto_20190211_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='objets',
            field=models.ManyToManyField(blank=True, related_name='objets', to='forum.Objet'),
        ),
    ]
