# Generated by Django 2.1.3 on 2019-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0100_perso_objets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultat',
            old_name='Lieu',
            new_name='lieu',
        ),
        migrations.AddField(
            model_name='action',
            name='appel_resultat',
            field=models.BooleanField(default=False, verbose_name='Appel un resultat auprès du MJ'),
        ),
        migrations.AlterField(
            model_name='action',
            name='interdit',
            field=models.BooleanField(default=False, verbose_name="interdit dans les lois d'arrakambre"),
        ),
    ]
