# Generated by Django 2.1.3 on 2019-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0102_commande_no_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'autre'), (1, 'fouille'), (2, 'bibliotheque'), (3, 'enquete'), (1, 'etude'), (3, 'exploration')], default=1),
        ),
    ]
