# Generated by Django 2.1.3 on 2019-02-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0103_auto_20190214_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultat',
            old_name='dommage',
            new_name='modif_PV',
        ),
        migrations.AlterField(
            model_name='resultat',
            name='type',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resultat_type', to='forum.Action'),
        ),
    ]
