# Generated by Django 2.1.3 on 2019-02-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0104_auto_20190214_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='type',
        ),
        migrations.AddField(
            model_name='resultat',
            name='action',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resultat_type', to='forum.Action'),
        ),
    ]
