# Generated by Django 2.1.3 on 2019-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0105_auto_20190214_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='cle1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Clé 1 - ';' sépare les entités "),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='cle2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Clé 2 - ';' sépare les entités "),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='cle_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clé Date'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='modif_PV',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='nom',
            field=models.CharField(max_length=30, null=True, verbose_name='Titre du resultat'),
        ),
    ]
