# Generated by Django 2.1.3 on 2019-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0106_auto_20190214_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='post_OK',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='fini',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='public',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='unique',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
