# Generated by Django 2.1.1 on 2019-02-24 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0109_remove_post_info_mj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField(verbose_name='')),
                ('nom_info', models.CharField(blank=True, default='', max_length=30, verbose_name="Nom informatique (image) - si =='' : rien n'est associé ")),
                ('dissimulation', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_jeu', models.CharField(blank=True, default='', max_length=50)),
                ('joueur_connaissant', models.ManyToManyField(blank=True, related_name='joueur_know_event', to='forum.Joueur')),
                ('lieu', models.ManyToManyField(blank=True, null=True, related_query_name='lieu_event', to='forum.Lieu')),
                ('persos_cible', models.ManyToManyField(blank=True, related_name='perso_cible_event', to='forum.Perso')),
            ],
        ),
    ]
