# Generated by Django 2.1.1 on 2019-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0110_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.ManyToManyField(blank=True, related_query_name='lieu_event', to='forum.Lieu'),
        ),
    ]
