# Generated by Django 2.1.3 on 2019-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0111_auto_20190224_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='MJ_only',
            field=models.BooleanField(default=False),
        ),
    ]
