# Generated by Django 2.1.1 on 2019-03-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0113_auto_20190301_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_combat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('nom_info', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('bonus', models.SmallIntegerField(default=0)),
                ('choix_defaut', models.BooleanField(default=True, verbose_name='Peut être une posture par défaut')),
                ('choix_attaque', models.BooleanField(default=False, verbose_name="Peut être une posture choisie lors de l'attaque")),
                ('PV_max', models.SmallIntegerField(default=10)),
                ('PV_min', models.SmallIntegerField(default=1)),
                ('categorie_combat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Categorie_combat')),
                ('commpetence_bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Competence', verbose_name='Apporte comme bonus la valeur de cette competence')),
                ('posture_neutralise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_neutralisee', to='forum.Posture', verbose_name='Posture qui neutralise les bonus de cette posture')),
            ],
        ),
    ]
