# Generated by Django 2.1.1 on 2019-03-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0114_categorie_combat_posture'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='posture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_perso', to='forum.Posture'),
        ),
        migrations.AddField(
            model_name='perso',
            name='posture_defaut_duel',
            field=models.ForeignKey(default=8, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posture_def_duel', to='forum.Posture'),
        ),
        migrations.AddField(
            model_name='perso',
            name='posture_defaut_melee',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posture_def_melee', to='forum.Posture'),
        ),
    ]
