# Generated by Django 2.1.1 on 2019-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0115_auto_20190304_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie_combat',
            name='nom_info',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
