# Generated by Django 2.1.1 on 2019-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0116_categorie_combat_nom_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='posture',
            name='multiplie_comp_bonus',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='posture',
            name='priorite',
            field=models.SmallIntegerField(default=1),
        ),
    ]
