# Generated by Django 2.1.1 on 2019-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0120_auto_20190306_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cible_posture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='cible_posture_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
