# Generated by Django 2.1.3 on 2019-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0121_auto_20190307_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='priorite',
            field=models.SmallIntegerField(default=1),
        ),
    ]
