# Generated by Django 2.1.3 on 2019-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0122_resultat_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='taille',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultat',
            name='repetable',
            field=models.BooleanField(default=True, verbose_name="n'est pas re-découvrable une 2e fois par un joueur qui connait déjà ce résultat"),
        ),
        migrations.AddField(
            model_name='resultat',
            name='users_connaissants',
            field=models.ManyToManyField(blank=True, related_name='connaissants_resultat', to='forum.Joueur'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='fini',
            field=models.BooleanField(default=False, verbose_name='est unique et a déjà été découvert'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='public',
            field=models.BooleanField(default=False, verbose_name='la découverte se fait un message public'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='unique',
            field=models.BooleanField(default=False, verbose_name="n'est pas re-découvrable une 2e fois même par un perso différent"),
        ),
    ]
