# Generated by Django 2.1.3 on 2019-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0123_auto_20190419_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='valeur_competence',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
