# Generated by Django 2.1.3 on 2019-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0124_resultat_valeur_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='T_date_jeu_fin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='T_date_jeu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
