# Generated by Django 2.1.3 on 2019-04-30 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0126_perso_espion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 14, 21, 54, 769601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 14, 21, 54, 769601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 14, 21, 54, 769601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 14, 21, 54, 753601, tzinfo=utc)),
        ),
    ]
