# Generated by Django 2.1.3 on 2019-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0128_auto_20190430_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perso_PV',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='perso_cache',
            field=models.BooleanField(default=False),
        ),
    ]
