# Generated by Django 2.1.3 on 2019-04-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0129_auto_20190430_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='perso_PV',
            new_name='perso_etatsante',
        ),
    ]
