# Generated by Django 2.1.3 on 2019-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0131_auto_20190430_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depart_lieu',
            field=models.BooleanField(default=False),
        ),
    ]
