# Generated by Django 2.1.3 on 2019-05-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0132_post_depart_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='objet_implique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Objet'),
        ),
    ]
