# Generated by Django 2.1.3 on 2019-05-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0134_action_implique_objet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='espion',
        ),
    ]
