# Generated by Django 2.1.3 on 2019-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0135_remove_perso_espion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
