# Generated by Django 2.1.3 on 2019-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0138_auto_20190607_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cibleperso_est_leader',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut être en train de mener le perso ou non'), (1, 'La cible ne doit pas être en train de mener le perso'), (2, 'La cible doit être en train de mener le perso'), (3, "La cible ne doit pas être en train de mener quelqu'un"), (4, "La cible doit être en train de mener quelqu'un")], default=0, verbose_name='Cible Perso : est en train de mener le perso ?'),
        ),
    ]
