# Generated by Django 2.1.3 on 2019-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0139_auto_20190607_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition_est_suivi',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso a des accompagnants ou non'), (1, "Ne peut etre fait que si le perso n'a pas d'accompagnant"), (2, 'Ne peut être fait que si le perso a des accompagnants')], default=0),
        ),
    ]
