# Generated by Django 2.1.3 on 2019-06-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0140_action_condition_est_suivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=30, unique=True)),
                ('nom_info', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite', models.SmallIntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='enfant', to='forum.Regle', verbose_name='Categorie de règle parent')),
            ],
        ),
    ]
