# Generated by Django 2.1.3 on 2019-06-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0141_regle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('nom_F', models.CharField(max_length=30, unique=True)),
                ('nom_info', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite', models.SmallIntegerField(default=1)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='charge', to='forum.Lieu', verbose_name="Donne la possession d'un lieu ")),
            ],
        ),
    ]
