# Generated by Django 2.1.3 on 2019-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0142_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='nom_F',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
