# Generated by Django 2.1.3 on 2019-06-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0143_auto_20190611_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Charge'),
        ),
    ]
