# Generated by Django 2.1.3 on 2019-06-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0144_perso_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=30, unique=True)),
                ('entete', models.BooleanField(default=True, verbose_name="le tableau a t'il une entete ?")),
                ('width', models.CharField(max_length=100, verbose_name='entrez la taille des colonnes, séparé par un #')),
                ('description', models.TextField(blank=True, null=True, verbose_name='un - devant chaque ligne, et un # pour séparer les colonnes')),
            ],
        ),
        migrations.AlterField(
            model_name='charge',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge', to='forum.Lieu', verbose_name="Donne la possession d'un lieu "),
        ),
        migrations.AlterField(
            model_name='regle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfant', to='forum.Regle', verbose_name='Categorie de règle parent'),
        ),
        migrations.AddField(
            model_name='regle',
            name='tableau1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regle1', to='forum.Tableau', verbose_name='#tableau1#'),
        ),
        migrations.AddField(
            model_name='regle',
            name='tableau2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regle2', to='forum.Tableau', verbose_name='#tableau2#'),
        ),
        migrations.AddField(
            model_name='regle',
            name='tableau3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regle3', to='forum.Tableau', verbose_name='#tableau3#'),
        ),
    ]
