# Generated by Django 2.1.3 on 2019-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0145_auto_20190612_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableau',
            name='nom_info',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
