# Generated by Django 2.1.3 on 2019-06-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0146_tableau_nom_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='entrez la taille des colonnes, séparé par un #'),
        ),
    ]
