# Generated by Django 2.1.3 on 2019-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0147_auto_20190613_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableau',
            name='titre_entete',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="titre pésent en tant qu'entête"),
        ),
    ]
