# Generated by Django 2.1.3 on 2019-06-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0148_tableau_titre_entete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regle',
            old_name='titre',
            new_name='nom',
        ),
    ]
