# Generated by Django 2.1.3 on 2019-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0149_auto_20190613_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regle',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
