# Generated by Django 2.1.3 on 2019-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0150_auto_20190619_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='visible_ds_regles',
            field=models.BooleanField(default=True),
        ),
    ]
