# Generated by Django 2.1.3 on 2019-06-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0151_action_visible_ds_regles'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='regle_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Regle'),
        ),
    ]
