# Generated by Django 2.1.3 on 2019-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0152_action_regle_associe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='PC',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='nbGardes_MAX',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='nbTroupes_MAX',
        ),
        migrations.AddField(
            model_name='perso',
            name='ds_groupe_temporaire',
            field=models.BooleanField(default=False),
        ),
    ]
