# Generated by Django 2.1.3 on 2019-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0154_auto_20190701_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='influence',
            field=models.SmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='lieu',
            name='influence',
            field=models.SmallIntegerField(default=15),
        ),
    ]
