# Generated by Django 2.1.3 on 2019-07-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0155_auto_20190702_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posture',
            name='posture_neutralise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_neutralisee', to='forum.Posture', verbose_name='Posture neutralisée par cette posture'),
        ),
    ]
