# Generated by Django 2.1.3 on 2019-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0156_auto_20190702_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='espace',
        ),
        migrations.AddField(
            model_name='commande',
            name='num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perso',
            name='secteur',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='taille',
            field=models.SmallIntegerField(default=1),
        ),
    ]
