# Generated by Django 2.1.3 on 2019-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0157_auto_20190710_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='PC',
            field=models.SmallIntegerField(default=0),
        ),
    ]
