# Generated by Django 2.1.3 on 2019-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0158_perso_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition_gardes',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso a des gardes ou non'), (1, "Ne peut etre fait que si le perso n'a pas de gardes"), (2, 'Ne peut être fait que si le perso a des gardes')], default=1),
        ),
        migrations.AddField(
            model_name='action',
            name='condition_troupes',
            field=models.SmallIntegerField(choices=[(0, 'Peut etre fait si le perso a des troupes ou non'), (1, "Ne peut etre fait que si le perso n'a pas de troupes"), (2, 'Ne peut être fait que si le perso a des troupes')], default=1),
        ),
    ]
