# Generated by Django 2.1.3 on 2019-07-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0159_auto_20190712_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='condition_gardes',
        ),
        migrations.RemoveField(
            model_name='action',
            name='condition_troupes',
        ),
    ]
