# Generated by Django 2.1.3 on 2019-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0161_auto_20190712_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cibleperso_mm_secteur',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut être dans le même secteur ou non'), (1, 'La cible doit être dans le même secteur'), (2, 'La cible ne doit pas être dans le même secteur')], default=1, verbose_name='Cible Perso : dans le même secteur ?'),
        ),
    ]
