# Generated by Django 2.1.3 on 2019-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0163_auto_20190712_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cibleperso_prisonnier',
            field=models.SmallIntegerField(choices=[(0, 'La cible peut être prisonnier ou non'), (1, 'La cible ne doit pas être prisonnier par un tiers'), (2, 'La cible doit être prisonnier par un tiers'), (3, 'La cible ne doit pas être prisonnier par le perso acteur'), (4, 'La cible doit être prisonnier par le perso acteur'), (5, 'La cible ne doit pas être prisonnier du tout')], default=1, verbose_name='Cible Perso : prisonnier ?'),
        ),
    ]
