# Generated by Django 2.1.3 on 2019-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0164_auto_20190712_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('priorite', models.SmallIntegerField(default=1)),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('nom_info', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_parle', models.BooleanField(default=True)),
                ('alphabet_commun', models.TextField(default='abcdefghijklmnopqrstuvwxyz0123456789éàè,.;', verbose_name='Alphabet Commun (caractères à la suite)')),
                ('alphabet_langue', models.TextField(default='', verbose_name='Alphabet Correspondant(; entre chaque caractère)')),
            ],
        ),
    ]
