# Generated by Django 2.1.3 on 2019-07-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0165_langage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='langage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_query_name='post_langage', to='forum.Langage'),
        ),
        migrations.AddField(
            model_name='post',
            name='texteVO',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
