# Generated by Django 2.1.3 on 2019-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0166_auto_20190715_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texteVO',
            field=models.TextField(blank=True, null=True, verbose_name='Texte dans la langue'),
        ),
    ]
