# Generated by Django 2.1.3 on 2019-07-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0168_auto_20190715_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editable',
            field=models.BooleanField(default=False, verbose_name='editable par le joueur avant validation'),
        ),
    ]
