# Generated by Django 2.1.3 on 2019-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0169_post_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='delai_edit',
            field=models.SmallIntegerField(default=5, verbose_name='Delai laisser pour éditer son post en minute'),
        ),
    ]
