# Generated by Django 2.1.3 on 2019-07-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0170_jeu_delai_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_perso', to='forum.Perso'),
        ),
    ]
