# Generated by Django 2.1.3 on 2019-07-17 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0171_auto_20190716_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='editable',
        ),
        migrations.AddField(
            model_name='post',
            name='date_initiale',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date initiale de création'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Publication'),
        ),
    ]
