# Generated by Django 2.1.3 on 2019-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0172_auto_20190717_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.TextField(default=''),
        ),
    ]
