# Generated by Django 2.1.3 on 2019-07-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0173_post_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='info_signature',
        ),
    ]
