# Generated by Django 2.1.1 on 2019-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0176_jeu_lock_onload'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='condition_competence_necessaire',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
