# Generated by Django 2.1.1 on 2019-08-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0177_auto_20190728_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cible_resultat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='cible_resultat_verbose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='resultat_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultat_cible', to='forum.Resultat'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='public',
            field=models.BooleanField(default=False, verbose_name='la découverte se fait par un message public'),
        ),
    ]
