# Generated by Django 2.1.1 on 2019-08-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0178_auto_20190814_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='texte_reussite',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Texte si reussite'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='repetable',
            field=models.BooleanField(default=False, verbose_name='est répétable : re-découvrable une 2e fois par un joueur qui connait déjà ce résultat'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='unique',
            field=models.BooleanField(default=False, verbose_name="est unique : n'est pas re-découvrable une 2e fois même par un perso différent"),
        ),
    ]
