# Generated by Django 2.1.1 on 2019-08-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0179_auto_20190817_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='chance_reussite',
            field=models.SmallIntegerField(default=100, verbose_name='chance_reussite : si reussi --> cf texte si réussite, si raté --> cf texte'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='priorite',
            field=models.SmallIntegerField(default=1, verbose_name="priorite : ponderation si choix aléatoire d'un resultat dans une liste (ex : rumeur)"),
        ),
    ]
