# Generated by Django 2.1.3 on 2019-09-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0182_auto_20190910_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objet_perso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('etat', models.SmallIntegerField(default=1)),
                ('porte', models.BooleanField(default=False)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possedant', to='forum.Objet', verbose_name='objet concerne')),
            ],
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='nbgarde',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='nbgarde_max',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='nbtroupe',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='nbtroupe_max',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='arme',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='armure',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='en_main',
        ),
        migrations.RemoveField(
            model_name='perso',
            name='objets',
        ),
        migrations.AddField(
            model_name='charge',
            name='gardes',
            field=models.BooleanField(default=False, verbose_name='Peut recevoir des gardes de son lieu, mais ne peut pas en donner à un autre perso'),
        ),
        migrations.AddField(
            model_name='charge',
            name='troupes',
            field=models.BooleanField(default=False, verbose_name='Peut recevoir des troupes de son lieu, mais ne peut pas en donner à un autre perso'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge', to='forum.Lieu', verbose_name="Donne la possession d'un lieu"),
        ),
        migrations.AddField(
            model_name='objet_perso',
            name='perso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objet', to='forum.Perso', verbose_name="perso qui a l'objet"),
        ),
    ]
