# Generated by Django 2.1.3 on 2019-09-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0184_auto_20190911_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='objet_implique',
            new_name='objet',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_attaque_duel',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_attaque_melee',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_aura',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_concentration',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_defense_duel',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_defense_melee',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_dissimulation',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_enquete',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_fouille',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_fuite',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_initiative',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_intrusion',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_officier',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_regeneration',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_savoir',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='bonus_soins',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='niveau_alchimie',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='niveau_armurerie',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='niveau_sorcellerie',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='pouvoir',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='puissance',
        ),
        migrations.AddField(
            model_name='objet',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_declenche', to='forum.Action', verbose_name="action : si Null, on ne peut pas utiliser l'objet"),
        ),
        migrations.AddField(
            model_name='objet',
            name='bonus_PC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objet',
            name='bonus_PE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objet',
            name='bonus_PV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objet',
            name='buff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objet',
            name='competence_bonifie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_comp_bonus', to='forum.Competence'),
        ),
        migrations.AddField(
            model_name='objet',
            name='competence_requise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_bonus', to='forum.Competence'),
        ),
        migrations.AddField(
            model_name='objet',
            name='delay',
            field=models.SmallIntegerField(default=0, verbose_name="Delai : duree de l'effet en heure"),
        ),
        migrations.AddField(
            model_name='objet',
            name='niveau_requis',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objet',
            name='posture_bonifie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obj_posture_bonus', to='forum.Posture'),
        ),
        migrations.AddField(
            model_name='objet',
            name='special',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='objet',
            name='valeur1',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objet',
            name='valeur2',
            field=models.SmallIntegerField(default=0, verbose_name="valeur2 ; pour arme s'agit du bonus/malus pour melee"),
        ),
        migrations.AddField(
            model_name='objet',
            name='valeur3',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objet',
            name='valeur4',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objet_perso',
            name='buff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objet_buff', to='forum.Objet', verbose_name='Buff'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='bonus_PA',
            field=models.BooleanField(default=False),
        ),
    ]
