# Generated by Django 2.1.3 on 2019-09-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0185_auto_20190912_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('priorite', models.SmallIntegerField(default=1)),
                ('nom', models.CharField(max_length=30)),
                ('nom_info', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfant', to='forum.Background', verbose_name='Categorie de règle parent')),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='objet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Objet_perso'),
        ),
    ]
