# Generated by Django 2.1.3 on 2019-09-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0187_auto_20190917_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='classe',
            field=models.CharField(choices=[('arme', 'arme'), ('armure', 'armure'), ('potion', 'potion'), ('parchemin', 'parchemin'), ('artefact', 'artefact'), ('quete', 'objet de quete'), ('', 'divers')], default='', max_length=100),
        ),
    ]
