# Generated by Django 2.1.3 on 2019-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0191_objet_rune_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='classe',
            field=models.CharField(choices=[('arme', 'arme'), ('armure', 'armure'), ('potion', 'potion'), ('parchemin', 'parchemin'), ('rituel', 'grimoire de rituel'), ('artefact', 'artefact'), ('quete', 'objet de quete'), ('', 'divers')], default='', max_length=100),
        ),
    ]
