# Generated by Django 2.1.3 on 2019-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0192_auto_20190920_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='OK_ds_post_action',
            field=models.BooleanField(default=False, verbose_name="OK_ds_post_action : si l'action n'est pas visible, on peut quand même accéder au formulaire par un autre lien"),
        ),
    ]
