# Generated by Django 2.1.3 on 2019-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0193_action_ok_ds_post_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='bonus_combat',
            field=models.BooleanField(default=False),
        ),
    ]
