# Generated by Django 2.1.3 on 2019-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0194_objet_bonus_combat'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='nom_effet',
            field=models.CharField(blank=True, default=True, max_length=30, verbose_name="Si l'objet génère un effet (potion, poison..), indique ce nom dans la fiche perso"),
        ),
        migrations.AlterField(
            model_name='objet',
            name='classe',
            field=models.CharField(choices=[('arme', 'arme'), ('armure', 'armure'), ('potion', 'potion'), ('poison', 'poison'), ('parchemin', 'parchemin'), ('rituel', 'grimoire de rituel'), ('artefact', 'artefact'), ('quete', 'objet de quete'), ('', 'divers')], default='', max_length=100),
        ),
    ]
