# Generated by Django 2.1.3 on 2019-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0198_auto_20191001_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='effet_perso',
            name='obj_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effet_obj', to='forum.Objet'),
        ),
        migrations.AlterField(
            model_name='effet_perso',
            name='objet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effet_objet', to='forum.Objet_perso'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='nom_effet',
            field=models.CharField(blank=True, default=True, max_length=30, verbose_name="nom_effet : Si l'objet génère un effet (potion, poison..), indique ce nom dans la fiche perso"),
        ),
    ]
