# Generated by Django 2.1.3 on 2019-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0199_auto_20191001_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objet_perso',
            name='buff',
        ),
        migrations.AddField(
            model_name='effet',
            name='special',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='effet_perso',
            name='valeur',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='objet',
            name='delay',
            field=models.SmallIntegerField(default=100, verbose_name="delay : Pour arme = valeur d'initiative en %, si Action ou Effet : durée de l'action ou de l'effet"),
        ),
    ]
