# Generated by Django 2.1.3 on 2019-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0200_auto_20191002_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='effet',
            name='infini',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='effet_perso',
            name='infini',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objet',
            name='effet_si_porte',
            field=models.BooleanField(default=False, verbose_name="effet_si_porte : si True, on n'a pas besoin d'utiliser l'objet, mais juste de le porter pour avoir son Effet"),
        ),
        migrations.AddField(
            model_name='perso',
            name='ID_nom_info',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='perso',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
