# Generated by Django 2.1.3 on 2019-10-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0201_auto_20191008_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet_perso',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tresor', to='forum.Resultat', verbose_name="resultat : dans quel resultat est l'objet"),
        ),
        migrations.AlterField(
            model_name='objet_perso',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possedant', to='forum.Objet', verbose_name='obj: objet concerne'),
        ),
        migrations.AlterField(
            model_name='objet_perso',
            name='perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objet', to='forum.Perso', verbose_name="perso : perso qui a l'objet"),
        ),
    ]
