# Generated by Django 2.1.3 on 2019-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0202_auto_20191008_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effet',
            name='priorite',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='buff',
        ),
        migrations.AddField(
            model_name='effet',
            name='effet_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='effet',
            name='nom_visible',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
