# Generated by Django 2.1.3 on 2019-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0203_auto_20191009_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='effet',
            name='niv_priorite',
            field=models.SmallIntegerField(default=1),
        ),
    ]
