# Generated by Django 2.1.3 on 2019-10-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0204_effet_niv_priorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effet',
            name='effet_suivant',
        ),
        migrations.AddField(
            model_name='effet',
            name='fonction_suivant',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="fonction_suivant : lance la fonction a la fin du delai. si Null, l'effet s'arrete"),
        ),
    ]
