# Generated by Django 2.1.3 on 2019-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0206_auto_20191011_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effet',
            name='support',
            field=models.CharField(blank=True, choices=[('perso', 'perso'), ('arme', 'arme'), ('armure', 'armure'), ('', 'divers')], default='', max_length=100),
        ),
    ]
