# Generated by Django 2.1.3 on 2019-10-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0207_auto_20191011_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='doppelganger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perso_original', to='forum.Perso', verbose_name='doppleganger : Si Doppelganger, copie du perso original'),
        ),
        migrations.AlterField(
            model_name='objet',
            name='nom_effet',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="nom_effet : Si l'objet génère un effet (potion, poison..), indique ce nom dans la fiche perso"),
        ),
    ]
