# Generated by Django 2.1.3 on 2019-10-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0210_auto_20191014_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='priorite_temp',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perso',
            name='doppelganger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perso_original', to='forum.Perso', verbose_name='doppelganger : Si Doppelganger, copie du perso original'),
        ),
    ]
