# Generated by Django 2.1.3 on 2019-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0211_auto_20191014_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='nom_origine',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
