# Generated by Django 2.1.3 on 2019-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0212_perso_nom_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='effet_perso',
            name='special',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
