# Generated by Django 2.1.3 on 2019-10-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0213_effet_perso_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effet_perso',
            name='special',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
