# Generated by Django 2.1.3 on 2019-10-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0214_auto_20191016_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persos_presents', to='forum.Lieu'),
        ),
    ]
