# Generated by Django 2.1.3 on 2019-10-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0216_auto_20191018_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effet_perso',
            name='obj_initial',
        ),
        migrations.AddField(
            model_name='effet_perso',
            name='objet_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effet_obj', to='forum.Objet'),
        ),
        migrations.AddField(
            model_name='objet_perso',
            name='valeur',
            field=models.SmallIntegerField(default=0, verbose_name="valeur : puissance de l'objet (pas pour arme et armure)/ si =0, alors prend valeur1 de obj"),
        ),
        migrations.AlterField(
            model_name='objet_perso',
            name='etat',
            field=models.SmallIntegerField(default=1, verbose_name='état : quantité pour objet cumulable/pour objet réparable : 2=OK, 1=cassé'),
        ),
    ]
