# Generated by Django 2.1.3 on 2019-11-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0217_auto_20191018_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description2 : se genere automatiquement'),
        ),
        migrations.AddField(
            model_name='action',
            name='lock_description2',
            field=models.BooleanField(default=False, verbose_name='si oui, description2 ne se genere pas automatiquement'),
        ),
        migrations.AlterField(
            model_name='effet_perso',
            name='objet_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effet_obj', to='forum.Objet_perso'),
        ),
    ]
