# Generated by Django 2.1.3 on 2019-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0218_auto_20191104_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='ciblelieu_discret',
            field=models.SmallIntegerField(choices=[(0, 'Le lieu cible peut être un lieu discret ou non'), (1, 'Le lieu cible ne doit pas être un lieu discret'), (2, 'Le lieu cible doit être un lieu discret')], default=0, verbose_name='Cible Lieu : est un lieu discret ?'),
        ),
    ]
