# Generated by Django 2.1.3 on 2019-11-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0219_action_ciblelieu_discret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perso',
            name='accepte_combat',
        ),
        migrations.AddField(
            model_name='jeu',
            name='regle_index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Regle'),
        ),
    ]
