# Generated by Django 2.1.3 on 2019-11-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0221_resultat_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='texte_reussite',
        ),
        migrations.AddField(
            model_name='resultat',
            name='echec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultat_echec', to='forum.Resultat', verbose_name='echec : si echec possible (avec chance_reussite<100 ou competence trop faible), peut amener a cet autre resultat'),
        ),
    ]
