# Generated by Django 2.1.3 on 2019-11-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0222_auto_20191112_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='obj_necessaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessaire_pr_resultat', to='forum.Objet'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='possible_pour_tous',
            field=models.BooleanField(default=True, verbose_name='possible_pour_tous : si False, alors juste les joueurs ci-dessous peuvent être concerné par ce resultat'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='resultat_trouve',
            field=models.ManyToManyField(blank=True, related_name='_resultat_resultat_trouve_+', to='forum.Resultat'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='users_connaissants',
            field=models.ManyToManyField(blank=True, related_name='connait_resultat', to='forum.Joueur'),
        ),
    ]
