# Generated by Django 2.1.3 on 2019-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0226_auto_20191115_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='effet',
            name='bonus_defense',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effet',
            name='bonus_dommage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effet',
            name='bonus_endurance',
            field=models.SmallIntegerField(default=0),
        ),
    ]
