# Generated by Django 2.1.3 on 2019-11-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0228_auto_20191115_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comportement_intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('nom_info', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite', models.SmallIntegerField(default=1)),
                ('OK_hote', models.BooleanField(default=False)),
                ('OK_perso', models.BooleanField(default=False)),
            ],
        ),
    ]
