# Generated by Django 2.1.3 on 2019-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0229_comportement_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comportement_intervention',
            name='nom',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
