# Generated by Django 2.1.3 on 2019-11-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0230_auto_20191119_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='comportement_intervention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Comportement_intervention'),
        ),
    ]
