# Generated by Django 2.1.3 on 2019-11-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0232_perso_rejete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perso',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perso_charge', to='forum.Charge'),
        ),
    ]
