# Generated by Django 2.1.3 on 2019-12-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0233_auto_20191122_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='obj_prioritaire',
            field=models.BooleanField(default=True, verbose_name="obj_prioritaire :  si obj_necessaire : si le perso a l'objet, alors il découvrira automatiquement ce resultat (résultat prioritaire sur d'autres et succés obligatoire même s'il n'a pas les compétences requises) --> le resultat ne peut pas être répétable"),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='obj_necessaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessaire_pr_resultat', to='forum.Objet', verbose_name="obj_necessaire : sans cet objet, le resultat n'est pas trouvable"),
        ),
    ]
