# Generated by Django 2.1.3 on 2019-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0237_auto_20191205_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='chance_reussite',
        ),
        migrations.AlterField(
            model_name='resultat',
            name='obj_prioritaire',
            field=models.SmallIntegerField(choices=[(0, "suffisant pour avoir le résultat, mais n'est pas nécessaire"), (1, "Nécessaire pour avoir le résultat, mais n'est pas suffisant"), (2, 'Nécessaire et suffisant pour avoir le résultat')], default=1),
        ),
    ]
