# Generated by Django 2.1.3 on 2019-12-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0238_auto_20191206_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultat',
            old_name='obj_prioritaire',
            new_name='obj_importance',
        ),
    ]
