# Generated by Django 2.1.3 on 2019-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0239_auto_20191206_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='obj_prioritaire',
            field=models.BooleanField(default=True, verbose_name="obj_prioritaire :  si obj_necessaire : si le perso a l'objet, alors ce résultat sera prioritaire sur d'autres --> le resultat ne peut pas être répétable"),
        ),
    ]
