# Generated by Django 2.1.3 on 2019-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0240_resultat_obj_prioritaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langage',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='langage',
            name='niveau',
        ),
        migrations.AddField(
            model_name='perso',
            name='langage',
            field=models.ManyToManyField(blank=True, related_name='langage_persos', to='forum.Langage', verbose_name='langage : Langages connus en plus du commun'),
        ),
        migrations.AddField(
            model_name='post',
            name='joueur_traduit',
            field=models.ManyToManyField(blank=True, related_name='posts_traduits', to='forum.Joueur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='texteVO',
            field=models.TextField(blank=True, null=True, verbose_name='texteVO : Texte dans la langue'),
        ),
    ]
