# Generated by Django 2.1.1 on 2019-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0241_auto_20191213_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='accompagnants_MAX',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perso',
            name='gardes_MAX',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perso',
            name='troupes_MAX',
            field=models.SmallIntegerField(default=0),
        ),
    ]
