# Generated by Django 2.1.3 on 2020-01-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0242_auto_20191229_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='bonus_aura',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lieu',
            name='gestion_gardes',
            field=models.BooleanField(default=True, verbose_name="gestion_gardes : si True, l'hote peut donner des gardes a qui bon lui semble"),
        ),
        migrations.AlterField(
            model_name='charge',
            name='influence',
            field=models.SmallIntegerField(default=1),
        ),
    ]
