# Generated by Django 2.1.3 on 2020-01-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0243_auto_20200106_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='influence',
            new_name='prestige',
        ),
    ]
