# Generated by Django 2.1.3 on 2020-01-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0245_auto_20200106_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge', to='forum.Lieu', verbose_name='lieu : charge relie a ce lieu'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='influence',
            field=models.SmallIntegerField(default=100, verbose_name='influence : valeur auto'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nb_voix_senat',
            field=models.SmallIntegerField(default=0, verbose_name='nb_voix_senat : valeur auto'),
        ),
        migrations.AlterField(
            model_name='perso',
            name='maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persos_maison', to='forum.Maison'),
        ),
    ]
