# Generated by Django 2.1.3 on 2020-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0247_auto_20200106_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='pct_prestige',
            field=models.SmallIntegerField(default=100),
        ),
    ]
