# Generated by Django 2.1.3 on 2020-01-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0248_maison_pct_prestige'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='pct_prestige',
        ),
    ]
