# Generated by Django 2.1.3 on 2020-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0249_remove_maison_pct_prestige'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='pct_prestige',
            field=models.SmallIntegerField(default=0, verbose_name='pct_prestige : valeur temporaire et auto'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='influence',
            field=models.SmallIntegerField(default=0, verbose_name='influence : valeur temporaire et auto'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nb_voix_senat',
            field=models.SmallIntegerField(default=0, verbose_name='nb_voix_senat : valeur temporaire et auto'),
        ),
    ]
