# Generated by Django 2.1.3 on 2020-01-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0250_auto_20200107_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loi',
            name='votes',
        ),
    ]
