from django.contrib import admin
from .models import *



admin.site.register(Maison)
admin.site.register(Lieu)
admin.site.register(Perso)
admin.site.register(Post)
admin.site.register(Competence)
admin.site.register(Action)
admin.site.register(Joueur)
#admin.site.register(Sante)
#admin.site.register(Categorie_competence)
admin.site.register(Commande)
admin.site.register(Atelier)
#admin.site.register(Espece)
admin.site.register(Jeu)
#admin.site.register(Mois)
admin.site.register(Categorie_action)
admin.site.register(Loi)
admin.site.register(Message)
admin.site.register(Resultat)
#admin.site.register(Evenement)
admin.site.register(Posture)
admin.site.register(Categorie_combat)
admin.site.register(Regle)
admin.site.register(Tableau)
admin.site.register(Langage)
admin.site.register(Background)
admin.site.register(Charge)
admin.site.register(Objet)
admin.site.register(Objet_perso)
admin.site.register(Effet)
admin.site.register(Effet_perso)
admin.site.register(Comportement_intervention)